version: '2'
networks:
  elk:
   driver: bridge
#   attachable: true
services:

  elasticsearch:
    image: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - /opt/esdata:/usr/share/elasticsearch/data
#     - data:/data:rw
    hostname: elasticsearch
    networks:
     - elk
    restart: on-failure

  logstash:
    image: logstash
    hostname: logstash
    networks:
     - elk
    command: ["-f", "/config-dir/logstash.conf"]
    ports:
     - "9500:9500"
    restart: unless-stopped
    volumes:
     - /root/ELK/config-dir:/config-dir
    depends_on:
     - elasticsearch

  kibana:
    image: kibana
    restart: on-failure
    hostname: kibana
    networks:
     - elk
    ports:
     - "80:5601"
    restart: on-failure
    depends_on:
     - elasticsearch

  rsyslog:
    hostname: rsyslog
    image: voxxit/rsyslog
    ports:
     - "514:514/tcp"
     - "514:514/udp"
    volumes:
     - ./rsyslog.d:/etc/rsyslog.d
     - /var/log:/var/log
    restart: on-failure
    networks:
     - elk

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
#    links:
#      - prometheus:prometheus
    ports:
     - "3000:3000"
    networks:
     - elk
    volumes:
     - ./data/grafana:/var/lib/grafana
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT  # logit: admin  password: MYPASSWORT
     - GF_USERS_ALLOW_SIGN_UP=false
     - GF_SERVER_DOMAIN=myrul.com
     - GF_SMTP_ENABLED=true
     - GF_SMTP_HOST=smtp.gmail.com:587
     - GF_SMTP_USER=a.zasymovych@terrasoft.ru
     - GF_SMTP_PASSWORD=mypassword
     - GF_SMTP_FROM_ADDRESS=a.zasymovych@terrasoft.ru
    depends_on:
     - elasticsearch
